// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createMockSupabaseClient } from './mockClient';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// When the env vars are missing (e.g. the public demo link), the app runs
// fully offline against seeded demo data stored in localStorage.
export const isDemoMode = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase: any = isDemoMode
  ? createMockSupabaseClient()
  : createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string);