// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjntypvfqpjxpcxhefsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbnR5cHZmcXBqeHBjeGhlZnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzczODYsImV4cCI6MjA1ODc1MzM4Nn0.16zvaqxKkarF0lRwQYQsnesVJ-gZZnSWcGx5LdkwemQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);